jobs:
  java_build:
    name: maven-compile (${{ matrix.os }}, JDK-${{ matrix.jdk }})
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: adopt
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      if: failure()
      name: Upload JVM crash logs
      uses: actions/upload-artifact@v4
      with:
        name: jvm-crash-logs
        path: /Users/runner/work/rocketmq/rocketmq/auth/hs_err_pid*.log
        retention-days: 1
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 8
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
name: Build and Run Tests by Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yaml
