jobs:
  misspell-check:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Install misspell
      run: 'curl -L -o ./install-misspell.sh https://git.io/misspell

        sh ./install-misspell.sh

        '
    - continue-on-error: true
      name: Run misspell
      run: find . -type f -print0 | xargs -0 bin/misspell -error -i transfered,derivate
name: Misspell Check
on:
  repository_dispatch:
    types: trigger-ga___misspell_check.yml
