jobs:
  dist-tar:
    name: Build distribution tar
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Build distribution tar
      run: 'mvn -Prelease-all -DskipTests -Dspotbugs.skip=true clean install -U

        '
    - continue-on-error: true
      name: Upload distribution tar
      uses: actions/upload-artifact@v3
      with:
        name: rocketmq
        path: distribution/target/rocketmq*/rocketmq*
    - continue-on-error: true
      name: Save PR number
      run: 'mkdir -p ./pr

        echo ${{ github.event.number }} > ./pr/NR

        '
    - continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: pr
        path: pr/
    timeout-minutes: 120
name: PR-CI
on:
  repository_dispatch:
    types: trigger-ga___pr-ci.yml
